# Generated by Django 2.2.3 on 2021-02-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210201_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Готово к доставке', 'Готово к доставке'), ('Доставлено', 'Доставлено')], max_length=200, null=True, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='pruduct',
            name='category',
            field=models.CharField(choices=[('Для дома', 'Для дома'), ('Для улицы', 'Для улицы')], max_length=200, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pruduct',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pruduct',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pruduct',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименования'),
        ),
        migrations.AlterField(
            model_name='pruduct',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
    ]
