# Generated by Django 2.2.3 on 2021-02-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210226_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(default='-', max_length=10000, null=True, verbose_name='Примечания'),
        ),
    ]
